### ISSUE TITLE
Marker not reached if clicking between markers

### ISSUE THREAD

**Issue by adrianpuescu** [spchuang/videojs-markers#12]
While testing the 'Dynamic video' example, I noticed that, if I click between the markers on the progress bar, the markers are not considered to be reached. Actually sometimes they are and sometimes they're not. Mostly not.

Would be great if the reached markers detection would work without any error between them as well. Consider a simple menu with some so called 'chapter' buttons which should be correlated with the markers and which should be styled differently when their corresponding "chapters" are played, even if the chapter was changed by clicking between markers on the progress bar. It doesn't look very well to have the 'Chapter 1' button styled as active while the user just jumped to 'Chapter 4'.

**Comment by spchuang** [comment]
That's a good idea. Since this may or may not be the behavior that everyone expects, I will add a Boolean option for "betweenMarkerReach". If it's true, the plugin will trigger the reach event when clicked in between the markers.

**Comment by spchuang** [comment]
Closing as commit#c7fb109f handles this request.
