### ISSUE TITLE
None of your demos work right now

### ISSUE THREAD

**Issue by hyperTwitch** [spchuang/videojs-markers#14]
I guess it looks like you updated how your plugin is called at some point which has caused your demos to all stop working. Here's a fixed jsbin version http://jsbin.com/goloyekevu/2/edit?html,output you may want to look into what broke your demo page though.

**Comment by spchuang** [comment]
The demo page seems to work for me.

**Comment by benbro** [comment]
Both demos don't work for me either.
The fixed version above work.
