### ISSUE TITLE
Markers are not working - Please can you fix them.

### ISSUE THREAD

**Issue by deekoder** [spchuang/videojs-markers#15]

**Comment by spchuang** [comment]
Can you provide more information -- browser, jquery version, console logs, so I can possibly reproduce it.

**Comment by jenswachtel** [comment]
Hi,

the link to your Jbin example seems to have a 404 inside the script
(https://rawgit.com/spchuang/videojs-markers/master/src/videojs.markers.css => 404)

If I go to your other demo (http://www.sampingchuang.com/videojs-markers)
I don't see any markers either. I am using Windows 8.1 with the latest Chrome browser

Thanks,
Jens

**Comment by spchuang** [comment]
mmm it's weird. The first time I load the page, the progress bar on the first demo doesn't work but the rests do. Then I refreshed the page a couple times, and everytime the progress bar is there.

Do you see any console logs?

**Comment by spchuang** [comment]
And I just fixed the jsbin example.

**Comment by jenswachtel** [comment]
Thanks btw. for this plugin!
Okay, this is what I get in Chrome (Windows 8.1). The overlay on top of the video works fine after a cuepoint got triggered. There are no errors, except the favicon.ico
![videoplayer - no marker](https://cloud.githubusercontent.com/assets/9703013/8207529/21bb7352-14d0-11e5-8e1a-533aaba10d5f.PNG)
