### ISSUE TITLE
Can't add markers

### ISSUE THREAD

**Issue by ldiebold** [spchuang/videojs-markers#20]
Thanks for writing this plugin, it's saved me a lot of time!
Just a couple of issues.

 - In your demo, adding a marker does nothing except on occasions where it adds a marker towards the end of the video.
 - Clicking "remove" seems to remove all markers except a couple.

tested on latest version of Chrome and Firefox with same result.

Thanks again :)

**Comment by spchuang** [comment]
Hi, if you look at the code for the demo:


    $(".remove").click(function(){
       player.markers.remove([1,2]);
    })
    $(".add").click(function(){
       player.markers.add([{
          time: 40,
          text: "I'm NEW"
       }]);
    });
 you'll see that add simply adds a marker at time 40 and remove removes the markers indexed at 1 and 2 (sorted by time). Hope that helps.

**Comment by ldiebold** [comment]
Ahh I see.

Thanks for your help!
