### ISSUE TITLE
marker display incomplete

### ISSUE THREAD

**Issue by xianlaioy** [spchuang/videojs-markers#21]
![qq 20150812174814](https://cloud.githubusercontent.com/assets/5875104/9221078/f7aec07a-4119-11e5-8579-7f3a4c53cd5d.jpg)

**Comment by spchuang** [comment]
Hi, can you be more specific on the issue?

**Comment by xianlaioy** [comment]
in dialog display incomplete
![1111](https://cloud.githubusercontent.com/assets/5875104/9242276/6c3e88b6-41b1-11e5-8a0d-ccb36287de02.jpg)

**Comment by spchuang** [comment]
I'm still not sure what the problem is. Do you mind showing a testing page so I can reproduce it myself? Thanks
