### ISSUE TITLE
How to insert pauses in the breakpoints ?

### ISSUE THREAD

**Issue by andreabr** [spchuang/videojs-markers#22]
Dear Spchuang, 

Your plugin is great. 

I have used it to study some video programming classes where I type in the IDE which is given in class video.
So, how to do, if possible, to insert a pause time in video on breakpoints ?

Is to watch part of the video, in the breakpoint the video pauses and I go type in IDE and then back to the video. Then, I could set a pause, for example, 30 secs at first breakpoint, 60 secs at second, etc...this would be more efficient for my class.

Brazil keepsakes for you.
Thanks so much.
André

**Comment by ldiebold** [comment]
Hi andreabr, I may be able to help.

As you may know, you can pass in options when you initialize the plugin.
The plugin has an "onMarkerReached" option so you could do something like this:

```javascript
videojs("video").ready(function(){

    var video = videojs('video');

    video.markers({
         onMarkerReached: function(marker) {
                  // pause the video
                  video.pause();
        {
    });

}
```

Does this help?

**Comment by spchuang** [comment]
@ldiebold provided a good example. 

If you would like to have a variable pause time for each marker (e.g. 30 sec at 1st and 60 seconds at 2nd), you could store the seconds to pause in each marker you pass to the plugin.

```javascript
var player = videojs('demo');

var markers =  [
   {time: 9.5, text: "pause 1", overlayText: "1", pauseTime: 30},
   {time: 16,  text: "pause 2", overlayText: "2", pauseTime: 60},
];

player.markers({
   onMarkerReached: function(marker){
      player.pause();
      setTimeout(function() {
         player.play();
      }, marker.pauseTime);
   },
   markers: markers
});
```

**Comment by andreabr** [comment]
Amigo, qual seria o problema ou o exemplo que voce queria para ver se posso te ajudar...

abraços

**Comment by sethbrandom** [comment]
Olá André. Obrigado por responder, poderia me disponibilizar algum e-mail para eu enviar o modelo que estou criando? 

Grato

**Comment by sethbrandom** [comment]
André estou tentando definir pausas nas marcações de capitulos do video

**Comment by andreabr** [comment]
andrezinhodorio at gmail
