### ISSUE TITLE
Videojs-markers with videojs-youtube

### ISSUE THREAD

**Issue by jorgepcbraz** [spchuang/videojs-markers#23]
I am having some problems when trying to use videojs-markers combined with videojs-youtube. 
Did you tested this? Is it possible?

**Comment by spchuang** [comment]
What's the problem? Can you be more specific

**Comment by jojo080889** [comment]
I'm having the same issue! The markers simply don't appear when loading a video with the videojs-youtube. The markers appear if I load a non-youtube video, though.

**Comment by rgw3d** [comment]
I also am having this issue - It works for non-videojs-youtube videos, but not with youtube videos

**Comment by clkao** [comment]
https://github.com/eXon/videojs-youtube/pull/340 fixes this issue.
