### ISSUE TITLE
Fix for broken demos/code due to deprecation of webkitMovementX/Y

### ISSUE THREAD

**Issue by mcanthony** [spchuang/videojs-markers#28]
Removing the prefixes to read movementX and movementY should do the trick. I don't think any browser should require the webkit prefix but if this is the case you could make this a conditional.

**Comment by spchuang** [comment]
I'm not sure what the issue is. Can you be more specific?

**Comment by mcanthony** [comment]
Oh sorry it was actually video.js which contained the deprecated prefixes, or at least the version of it being used in the jsbin demo. I don't think this is why the demo isn't working however, that seems to be related to broken links to assets. The version on your website is not available (as I am sure your aware your site is down).

I was just passing through and saw the deprecation notice when I was checking the console to see what might be wrong. I didn't pay close enough attention to notice the video.js plugin itself reporting the error and not your script. I am certain you can close this issue now sorry for the confusion.

**Comment by spchuang** [comment]
I see. Thanks for noticing! I brought the website back again.
