### ISSUE TITLE
Display images in markers

### ISSUE THREAD

**Issue by benbro** [spchuang/videojs-markers#29]
Is it possible to show a thumbnail instead of just text?
Something like:
https://github.com/brightcove/videojs-thumbnails

**Comment by spchuang** [comment]
Do you mean in the tooltip or in banner? And what is the use case here

**Comment by benbro** [comment]
In the tooltip.
The use case is to see a preview of what you'll see if you seek to this marker.

**Comment by spchuang** [comment]
I see. Yeah it's definitely possible. You can update modify the source code to display <img> instead of text for the tooltip. Do you want to send a pull request?

**Comment by L2o** [comment]
I changed line 250 :

`markerTip.querySelector('.vjs-tip-inner').innerText = setting.markerTip.text(marker);`
to
`markerTip.querySelector('.vjs-tip-inner').innerHTML = setting.markerTip.text(marker);`

So it process HTML tags, I think it's not the most crash-proof thing, but it might help.
