### ISSUE TITLE
Website with documentation not working

### ISSUE THREAD

**Issue by Albermg7** [spchuang/videojs-markers#30]
Hi:)
Sorry to post it here, since it is not actually an issue with the plugin itself. 
I just wanted to tell you that the website (http://sampingchuang.com/videojs-markers) is not working and the documentation was really usefull por me 

Thanks a lot for your work! Its quite good!

**Comment by spchuang** [comment]
Hey thanks for letting me know! I'll look into it and bring back the site.

Meanwhile, you can look at the doc from the source code: https://github.com/spchuang/sampingchuang/blob/master/app/templates/videojs-markers.html

**Comment by spchuang** [comment]
The website is up now.
