### ISSUE TITLE
non jQuery version ?

### ISSUE THREAD

**Issue by smarajitdasgupta** [spchuang/videojs-markers#34]
I would need to create video js ad markers and pretty much the very functionality this plugin covers already. However the player project code I am working on does not use jQuery and was wondering if there is a version of videojs-markers that can work without jquery?

**Comment by spchuang** [comment]
Hi, thanks for your interested in using the library. Unfortunately, I don't have a version without dependency on jQuery. You're certainly more than welcomed to convert the library to only use raw javascript for DOM manipulation.

An alternative (if jQuery is too heavy for your use case) is using other light weight DOM manipulation libraries like sizzle (a component of Jquery) or zepto. They might work directly out of the box with videojs-markers.
