### ISSUE TITLE
Add plugin to npm registry

### ISSUE THREAD

**Issue by martinbean** [spchuang/videojs-markers#39]
I tried to install this plugin using `npm install videojs-markers`, but got the following error:

```
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/videojs-markers
npm ERR! 404 
npm ERR! 404  'videojs-markers' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
```

Are you able to publish it, please?

**Comment by spchuang** [comment]
Just published!

**Comment by alekseykarpenko** [comment]
@spchuang how about updating README with new installation method via npm? found about availability on npm through github issues..
