### ISSUE TITLE
Compatibility for Video.js version 5

### ISSUE THREAD

**Issue by martinbean** [spchuang/videojs-markers#40]
Is this on the roadmap at all?

**Comment by spchuang** [comment]
hi @martinbean  thanks for your interest. I haven't been actively maintaining the plugin. I can take a look when I have more free time but you are certainly more than welcome to submit a fix so it's compatible with video.js 5!

**Comment by marianoarga** [comment]
+1

**Comment by sudha53633** [comment]
I've been updating to videojs 5, everything seems fine except position. Could you please provide inputs to set the the exact position for the marker. "left":  getPosition(marker) + '%'. 

Thanks,

**Comment by spchuang** [comment]
Hey guys, thanks for the wait.

I made some small tweaks so the style is compatible with videojs5. You can see try it out from the demo code `demo/example-videojs5.html` which uses videojs 5.11.8. The final code is pushed to version 0.7.0

If you have any more questios, please do open another issue! Thanks :)

**Comment by spchuang** [comment]
Another style work around for html 5 is we have to set z-index of the progress circle thing to be greater than the markers' z-index (which is set to 100). 
```
.video-js .vjs-time-tooltip, .video-js .vjs-play-progress:before, .video-js .vjs-play-progress:after {
    z-index: 101;
}

```
