### ISSUE TITLE
Formatting markerTip CSS

### ISSUE THREAD

**Issue by jaruche** [spchuang/videojs-markers#41]
Hi,

I see on the example that it is possible to customize the marker by setting CSS markerStyle.

How could I do the same for the markerTip? I would like to change the background color and size.

Thanks,
Fernando

**Comment by jaruche** [comment]
I found the styles:

`<style>
        .vjs-tip {
            font-size: 14px;
        }
        .vjs-tip .vjs-tip-inner {
            color: black;
            background-color: yellow;
        }
        .vjs-tip .vjs-tip-arrow {
            background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJCAYAAADgkQYQAAAAAXNSR0IArs4c6QAAAENJREFUGBmNzlEKACAIA9Dt/oc2DGZLQuqncC8VaCcC0UqgFxyQJyvkQB8FN3oBh5xAwXxMMEf+76S23lFLK7tuhwoWU/Ya/y97IuIAAAAASUVORK5CYII=") bottom left no-repeat;
        }
    </style>`

**Comment by spchuang** [comment]
Hi @jaruche  it certain makes sense to add "style" as a property for markerTips in the plugin. For now, feel free to override the default css classes (as you already found) to customize the style!

**Comment by spchuang** [comment]
The font size is relatively simple you can just override the css. The tricky thing is the background color. The bottom of the tooltip is a black rectangle image so you need to update the image too
