### ISSUE TITLE
merker reached event does not fire ontime on firefox

### ISSUE THREAD

**Issue by saeedalvand** [spchuang/videojs-markers#42]
I implemented a coed in which I needed to block seeking beyond a marker. It was fully working on chrome, but when I tested it on firefox, it didn't work. The reason is that "onMarkerReached" event is fired before "seeking" event and so I cannot check whether it has been called while playing or seeking.

**Comment by spchuang** [comment]
hi sorry to get back so late - were you able to figure out a fix?

**Comment by spchuang** [comment]
I created an example for preventing seeking : https://github.com/spchuang/videojs-markers/blob/master/demo/example-block-seeking.html

Let me know if that helps. I'm closing this issue now.
