### ISSUE TITLE
Markers not being updated on reset

### ISSUE THREAD

**Issue by mauricioklein** [spchuang/videojs-markers#47]
Hello!

It seems that the marker are not being updated on #reset call.

My markers are being created like this:

``` js
const player = window.player = window.videojs([my video conf here]);

player.markers({
   onMarkerReached: (marker) => {
      setAnnotationVisibility(marker.annotationRef, visibility);
   },
   markers: markers
});
```

> setAnnotationVisibility is my callback function
> annotationRef is a custom attribute

When loading a second video, I set video src (as usual) and update the markers with the following call:

``` js
// "markers" is an array of markers
player.markers.reset(markers)
```

However, even ensuring that the new markers are being passed correctly to #reset function, the old markers are still there, and the new ones are just ignored.

Am I doing something wrong here?

Thanks!

**Comment by mauricioklein** [comment]
Ok, I did some debug here and I'm sure the method is being called correctly.
In fact, I've changed the markers array by an empty array, just to be sure that the previous markers would be deleted: they weren't.

The strange part is: if I go to the browser console and call the #reset function manually, it works fine.

Any hint would be appreciated!

**Comment by mauricioklein** [comment]
@spchuang could you please take a look at this?
Any hint would be really appreciated.
Thanks!

**Comment by spchuang** [comment]
Hi, I will take a look this weekend! Sorry for the day - have been really swamped with work.

**Comment by mauricioklein** [comment]
Thanks @spchuang!

Please let me know if I can help in anything.

By the way, after some extra tests, calling getMarkers() from React works well, returning the old markers. The problem seems to be with something related to reset function.

Thanks!

**Comment by spchuang** [comment]
@mauricioklein  do you have an example of how I can reproduce this issue? I can reproduce it from the demo code (demo/example.html).

**Comment by mauricioklein** [comment]
@spchuang I'll try to create a demo app in React to reproduce this error, since I'm facing this using React.
Until the end of day I'll share with you this demo project.
About the code, I'm using the standards presented on videojs-markers example, nothing different from that.
Please let me know if I can help in something else in the meantime.
Thanks!

**Comment by spchuang** [comment]
When you tried the demo/example.html code, does the `reset` logic work for you?

**Comment by amitport** [comment]
adding 1sec delay between plugin initialization and reset fixes (bypasses) the issue for me

**Comment by mauricioklein** [comment]
Hello all!

So sorry about the loooong delay... Was involved in some other tasks and was able to come back to this one just now.

For some reason, after our last PR's merged on the project, the markers seems to be working well. The new ones are correctly loaded. Sorry but I can't explain exactly what was the problem.

But I'll keep @amitport suggestion in mind for future reference.

Thank you so much for all the support so far, and, again, sorry about the long delay.

**Comment by spchuang** [comment]
Thank!
