### ISSUE TITLE
Custom marker length 

### ISSUE THREAD

**Issue by apurvgandhwani** [spchuang/videojs-markers#54]
Is it possible to have marker length according to start time and endtime of marker? If yes then how?

**Comment by spchuang** [comment]
@apurvgandhwani by "marker length" do you mean the actual size of the marker UI (the dot)?

**Comment by apurvgandhwani** [comment]
Yes. That's what I mean.

**Comment by apurvgandhwani** [comment]
@spchuang can you please help me out?

**Comment by spchuang** [comment]
have you tried playing around with manually setting the marker length using jquery?

**Comment by tmm1** [comment]
For my use-case, I needed each marker to be of a different duration/width. I implemented this feature in https://github.com/tmm1/videojs-markers/compare/no-jquery...tmm1:marker-duration (it is built on top of #57. If that is merged, I will open a new PR for the marker duration features).

**Comment by spchuang** [comment]
will be added to newest package.
