### ISSUE TITLE
Plugin error, if no markers present at initializing

### ISSUE THREAD

**Issue by borzaka** [spchuang/videojs-markers#62]
If I initialize the plugin without any markers, it gives me error:

```
VIDEOJS: ERROR: TypeError: Cannot read property 'forEach' of undefined
at addMarkers (videojs-markers.js:147:17)
at initialize (videojs-markers.js:389:11)
[...]
```

I think the solution would be to check if there is a marker present in the `initialize()` function:
```javascript
if (setting.markers.length) {
    addMarkers(options.markers);
}
```

I'am planning to add markers later; for chapters based on the chapter track.

**Comment by spchuang** [comment]
can you pass in empty array [] for markers?

**Comment by spchuang** [comment]
Can you add empty array `[]` or markers?

**Comment by borzaka** [comment]
Yes, it's working, thank you! Now I can use the minified version :)

```js
markers: {
	markers: []
}
```

But you should consider add that if statement that I suggested for future proof.

**Comment by spchuang** [comment]
Good idea. Just updated the code to handle it more gracefully.
