### ISSUE TITLE
Need to add a marker depending of what is selected inside the player

### ISSUE THREAD

**Issue by sylvain94** [spchuang/videojs-markers#63]
Hello , 

I need to add a marker following the scene selected inside the player (not depeding of the javascript time)

   $(".add").click(function(){
      player.markers.add([{
            time: 25, // I don't know wich time I need bu implement it depeding the what I selected inside the player
            text: "marker"
         }]);

Exemple here 👍 
https://www.hostingpics.net/viewer.php?id=252248Sanstitre.png

Is there anyway to do it ?

Thanks

**Comment by borzaka** [comment]
Add a marker to the current time of the player:

```javascript
player.markers.add([{
      time: player.currentTime()
}]);
```

**Comment by sylvain94** [comment]
Many thanks for your help Borzaka. That's the need !

**Comment by spchuang** [comment]
Thanks for replying @borzaka !
