### ISSUE TITLE
Getting Error with videojs 5

### ISSUE THREAD

**Issue by shravanthanvi** [spchuang/videojs-markers#73]
Getting this errors
in the example given 
TypeError: _video2.default is undefined
videojs-markers.js:466:3

TypeError: player.markers is not a function
[Learn More]

**Comment by balindenberg** [comment]
Did you find a solution to this? I'm getting `_video2.default.registerPlugin is not a function` using Videojs 5.18.4

**Comment by balindenberg** [comment]
@shravanthanvi I used this distribution of Markers and it worked: https://cdnjs.cloudflare.com/ajax/libs/videojs-markers/0.7.0/videojs-markers.js

**Comment by spchuang** [comment]
Yes, use the newest release which support videojs 5
