### ISSUE TITLE
Problem with markers

### ISSUE THREAD

**Issue by Pekkonen** [spchuang/videojs-markers#75]
Hi. In your link
"JSBin Demo can be found here" - http://jsbin.com/vifilen/1/edit I don't see markers
But see many errors in Chrome console:
fs.js:36 Dave is ready.
fs.js:36 To edit settings, type this string into the console: octuc0tapclg
fs.js:72 XHR finished loading: POST "https://rs.fullstory.com/rec/page".
c.post @ fs.js:72
c.start @ fs.js:192
c.createRecorder @ fs.js:210
c.start @ fs.js:209
c.init @ fs.js:202
(anonymous) @ fs.js:215
(anonymous) @ fs.js:215
jquery-1.11.0.min.js:4 XHR finished loading: GET "http://jsbin.com/blog/all.json?Tue-Nov-21-2017".
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ jsbin-4.1.1.min.js:31
start @ jsbin-4.1.1.min.js:31
(anonymous) @ start.js?d32b:1
runner:26 Uncaught (in promise) DOMException: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
(anonymous) @ runner:26
Promise (async)
(anonymous) @ runner:26
runner-4.1.1.min.js:1 d[ o_0 ]b
jquery-1.11.0.min.js:4 XHR finished loading: GET "https://app.codesponsor.io/p/JoMssLSjQuR8acFXk_Lftw/message.json".
send @ jquery-1.11.0.min.js:4
ajax @ jquery-1.11.0.min.js:4
(anonymous) @ edit?html,js,output:603
runner-4.1.1.min.js:1 Script error. (line 0)
videojs-markers.js? [sm]:464 Uncaught TypeError: _video2.default.registerPlugin is not a function
    at videojs-markers.js? [sm]:464
    at videojs-markers.js:10
    at videojs-markers.js:13
(anonymous) @ videojs-markers.js? [sm]:464
(anonymous) @ videojs-markers.js:10
(anonymous) @ videojs-markers.js:13
runner-4.1.1.min.js:1 error TypeError: video.markers is not a function
    at http://null.jsbin.com/runner:7:9
runner:7 Uncaught TypeError: video.markers is not a function
    at runner:7

![image](https://user-images.githubusercontent.com/31384473/33069466-b6391c08-cec5-11e7-95db-4b9fad2b6260.png)

Demo from zip archive have same problem:
"Uncaught TypeError: _video2.default.registerPlugin is not a function
    at videojs-markers.js:466
    at videojs-markers.js:10
    at videojs-markers.js:13
example-block-seeking.html:52 Uncaught TypeError: player.markers is not a function
    at example-block-seeking.html:52"
And no markers has appearing

**Comment by spchuang** [comment]
HI, sorry it seems like in a previous commit (https://github.com/spchuang/videojs-markers/commit/8fd8d50ce2f960a6db328d3c8aadcaa02832380b) someone updated the code for videojs6. I'm reverting back the changes. Will push a new package. Thank you!
