### ISSUE TITLE
Miss dist folder when using npm and yarn

### ISSUE THREAD

**Issue by NarakuF** [spchuang/videojs-markers#81]
When I use 'npm install videojs-markers' and 'yarn add videojs-markers', it will miss dist folder in node_modules/videojs-markers.
![capture](https://user-images.githubusercontent.com/32041742/35238242-ec622ae6-ff7a-11e7-9c54-60be2ee43f71.PNG)

**Comment by rubanaan** [comment]
I have the same issue, did you already find a solution?

**Comment by webernir** [comment]
I reverted to previous version

**Comment by NarakuF** [comment]
@webernir Hi, it seems that dist folder is still missing, could you check it?

**Comment by webernir** [comment]
@NarakuF  I think it's still an issue.
i'm still working with previous version....

**Comment by NarakuF** [comment]
@spchuang Hi, it doesn't work, for v1.0.0

**Comment by rubanaan** [comment]
It's because the /dist/ directory is added to the .gitignore, right? Downgrading to v0.6.0 fixed the issue for me, but a fix in the last version would be nice!

**Comment by spchuang** [comment]
got it. Updating a new package 1.0.1 with the fix

**Comment by spchuang** [comment]
it should work now!

**Comment by rubanaan** [comment]
@spchuang Thanks, worked for me!
